#!/bin/sh
### BEGIN INIT INFO
# Provides:          nodessh
# Required-Start:    $local_fs $network $remote_fs $syslog
# Required-Stop:     $local_fs $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: nodessh for protonet
# Description:       This file should be used to start and stop nodessh.
### END INIT INFO

# Author: Martin Meier <martin.meier@protonet.info>

PATH=/sbin:/usr/sbin:/bin:/usr/bin
PIDFILE=/var/run/forever/nodessh.pid
LOGFILE=/var/log/nodessh.log
NODESSH_PATH=/opt/nodessh

nodessh_status()
{
  if [ ! -f $PIDFILE ] ; then
    # program not running
    return 3
  fi
  for pid in $(cat $PIDFILE) ; do
    if ! ps --no-headers p "$pid" | grep 'index.js' > /dev/null ; then
      # program running, bogus pidfile
      return 1
    fi
  done
  return 0
}

case "$1" in
  start)
  nodessh_status
  ret=$?
  case "$ret" in
    0)
      echo "nodessh is already running. Will not start."
    ;;
    *)
      exec forever start --sourceDir=$NODESSH_PATH --pidFile $PIDFILE -l $LOGFILE --append index.js
    ;;
  esac
  ;;

  stop)
  nodessh_status
  ret=$?
  case "$ret" in
    0)
      exec forever stop --sourceDir=$NODESSH_PATH -p /var/run/forever $NODESSH_PATH/index.js
    ;;
    *)
      echo "nodessh is not running. Nothing to stop."
    ;;
  esac
  ;;

  restart)
  nodessh_status
  ret=$?
  case "$ret" in
    0)
      exec forever restart $NODESSH_PATH/index.js
    ;;
    *)
      echo "nodessh not running. Starting ..."
      exec forever start --sourceDir=$NODESSH_PATH --pidFile $PIDFILE -l $LOGFILE --append index.js
    ;;
  esac
  ;;

  status)
  nodessh_status
  ret=$?
  case "$ret" in
  0)
    echo "nodessh is running."
  ;;
  1)
    echo "nodessh dead, but $PIDFILE exists."
  ;;
  *)
    echo "nodessh not running."
  ;;
  esac
    exit $ret
  ;;

  *)
  echo "Usage: service nodessh {start|stop|restart|status}"
  ;;
esac

exit 0

